const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const babel = require('@babel/core');

const root = path.join(__dirname, '..');
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8');

const loadModule = (relative) => {
  const filename = path.join(root, relative);
  const transformed = babel.transformFileSync(filename, {
    babelrc: false,
    configFile: false,
    plugins: [require.resolve('@babel/plugin-transform-modules-commonjs')],
  }).code;
  const instance = new Module(filename, module);
  instance.filename = filename;
  instance.paths = Module._nodeModulePaths(path.dirname(filename));
  instance._compile(transformed, filename);
  return instance.exports;
};

const appearance = loadModule('services/mapAppearance.js');
const coordinates = loadModule('utils/coordinates.js');
const profileValidation = loadModule('utils/profileValidation.js');
assert.equal(profileValidation.PROFILE_TITLE_OPTIONS.length, 10);
assert.equal(profileValidation.validateProfile({ name: 'Ana', location: 'Querétaro, Qro.', profileTitle: 'Promotor de Reciclaje', bio: 'Eco' }).field, 'name');
assert.equal(profileValidation.validateProfile({ name: 'Víctor Rodríguez', location: 'Qro', profileTitle: 'Promotor de Reciclaje', bio: 'Eco' }).field, 'location');
assert.equal(profileValidation.validateProfile({ name: 'Víctor Rodríguez', location: 'Querétaro, Qro.', profileTitle: '', bio: 'Eco' }).field, 'profileTitle');
assert.equal(profileValidation.validateProfile({ name: 'Víctor Rodríguez', location: 'Querétaro, Qro.', profileTitle: 'Promotor de Reciclaje', bio: 'Eco' }), null);
assert.equal(coordinates.isValidCoordinate(null), false);
assert.equal(coordinates.isValidCoordinate(undefined), false);
assert.equal(coordinates.isValidCoordinate([]), false);
assert.equal(coordinates.isValidCoordinate('[-100, 20]'), false);
assert.equal(coordinates.isValidCoordinate([0, 0]), false);
assert.equal(coordinates.isValidCoordinate([-100.3899, 20.5888]), true);
assert.equal(appearance.MAP_TIME_ZONE, 'America/Mexico_City');
assert.equal(appearance.getAutomaticLightPreset(new Date('2026-08-02T12:00:00Z')), 'dawn');
assert.equal(appearance.getAutomaticLightPreset(new Date('2026-08-02T15:00:00Z')), 'day');
assert.equal(appearance.getAutomaticLightPreset(new Date('2026-08-03T00:00:00Z')), 'dusk');
assert.equal(appearance.getAutomaticLightPreset(new Date('2026-08-03T02:00:00Z')), 'night');

process.env.EXPO_PUBLIC_MOBILE_LINKS_READY = 'false';
const links = loadModule('navigation/linking.js');
assert.equal(links.mobileShareUrl('posts', 42), 'zerowaste://posts/42');
assert.equal(links.mobileShareUrl('news', 'reciclaje-qro'), 'zerowaste://news/reciclaje-qro');
assert.throws(() => links.mobileShareUrl('posts', '../secret'));
assert.deepEqual(links.deepLinkTarget('zerowaste://posts/42'), { name: 'PostDetail', params: { id: '42' } });
assert.deepEqual(links.deepLinkTarget('https://www.zerowaste-qro.com/app/news/reciclaje-qro'), { name: 'NewsDetail', params: { articleId: 'reciclaje-qro' } });
assert.equal(links.deepLinkTarget('zerowaste://auth/google?code=redacted'), null);
assert.equal(links.deepLinkTarget('https://example.com/app/posts/42'), null);

const comments = read('components/forum/CommentsModal.js');
const notifications = read('services/mobileNotifications.js');
const navigator = read('navigation/AppNavigator.js');
const articles = read('screens/ArticleDetailScreen.js');
const forum = read('screens/ForumScreen.js');
const postDetail = read('screens/PostScreen.js');
const notificationsScreen = read('screens/NotificationsScreen.js');
const editorial = read('data/editorialContent.js');
const editProfile = read('screens/EditProfileScreen.js');
const settings = read('screens/SettingsScreen.js');
const collection = read('screens/CreateCollectionScreen.js');
const login = read('screens/LoginScreen.js');
const axiosClient = read('api/axios.js');
const routeNavigation = read('screens/RouteNavigationScreen.js');
const mapScreen = read('screens/MapScreen.js');
const homeScreen = read('screens/HomeScreen.js');
const createPost = read('screens/CreatePostScreen.js');
const profileScreen = read('screens/ProfileScreen.js');
const pointDetail = read('screens/PointDetailScreen.js');
const app = read('App.js');
const appConfig = JSON.parse(read('app.json'));
const imageUpload = loadModule('utils/imageUpload.js');

assert.match(comments, /parent_comment_id/);
assert.match(comments, /KeyboardAvoidingView/);
assert.match(comments, /Platform\.OS === 'ios' \? 'padding' : 'height'/);
assert.match(comments, /Escribe un comentario/);
assert.match(comments, /style=\{\{ flex: 1 \}\}/);
assert.match(comments, /keyboardDidHide/);
assert.match(comments, /Keyboard\.scheduleLayoutAnimation\(event\)/);
assert.doesNotMatch(comments, /keyboardLayoutRevision|keyboardRestoreY|Animated\.add/);
assert.match(comments, /navigationBarTranslucent=\{false\}/);
assert.match(comments, /keyboardVisibleRef/);
assert.doesNotMatch(comments, /inputRef\.current\?\.blur\(\)/);
assert.match(comments, /highlightCommentId/);
assert.match(notifications, /getExpoPushTokenAsync/);
assert.match(notifications, /expoPushToken/);
assert.doesNotMatch(notifications, /sound:\s*'default'/);
assert.match(navigator, /getLastNotificationResponseAsync/);
assert.match(navigator, /addNotificationResponseReceivedListener/);
assert.match(navigator, /addPushTokenListener/);
assert.match(articles, /mobileShareUrl/);
assert.doesNotMatch(forum, /\/foro\/\$\{post\.id\}/);
assert.match(postDetail, /<CommentsModal/);
assert.doesNotMatch(postDetail, /api\.get\(`\/foro\/posts\/\$\{postId\}\/respuestas`\)/);
assert.doesNotMatch(postDetail, /<FlatList/);
assert.match(notificationsScreen, /\/usuarios\/me\/notificaciones/);
assert.match(editorial, /Querétaro fortalece la gestión de sus residuos/);
assert.match(editorial, /references:/);
assert.doesNotMatch(editorial, /Linking\.openURL|WebView/);
assert.doesNotMatch(editorial, /<\/?[a-z][^>]*>/i);
assert.match(editProfile, /PROFILE_TITLE_OPTIONS\.map/);
assert.match(editProfile, /showDialog\(\{ type: 'error'/);
assert.match(editProfile, /maxLength=\{100\}/);
assert.match(settings, /notificationRows\.map\(\(\{ key, \.\.\.row \}/);
assert.match(settings, /Animated\.parallel/);
assert.match(settings, /trackOpacity/);
assert.match(settings, /reduceMotionChanged/);
assert.match(collection, /searchAddresses/);
assert.match(collection, /setCoordinates\(suggestion\.coordinates\)/);
assert.match(collection, /MATERIAL_OPTIONS/);
assert.match(collection, /selectedMaterials\.join\(', '\)/);
assert.match(collection, /KeyboardAvoidingView/);
assert.match(collection, /collectorOnly/);
assert.match(login, /REMEMBER_LOGIN_KEY/);
assert.match(login, /persist: rememberMe/);
assert.match(login, /navigationBarTranslucent=\{false\}/);
assert.match(login, /paddingBottom: Math\.max\(insets\.bottom, 24\)/);
assert.match(axiosClient, /Usuario o contraseña incorrectos/);
assert.match(routeNavigation, /mapbox\.mapbox-traffic-v1/);
assert.match(routeNavigation, /paddingTop: topSafeInset \+ 12/);
assert.match(routeNavigation, /paddingBottom: bottomSafeInset \+ 12/);
assert.match(routeNavigation, /height: bottomSafeInset/);
assert.doesNotMatch(routeNavigation, /label="DISTANCIA"/);
assert.match(mapScreen, /styleURL=\{usingFallbackStyle \? MAP_FALLBACK_STYLE_URL : MAP_STYLE_URL\}/);
assert.match(mapScreen, /<Mapbox\.StyleImport/);
assert.match(mapScreen, /show3dBuildings: false/);
assert.match(homeScreen, /loadingClassName="bg-white"/);
assert.doesNotMatch(homeScreen, /setInterval\(\(\) => setHomeRefreshKey/);
assert.match(createPost, /validatePickedProfileImage/);
assert.match(profileScreen, /function ProfileSkeleton/);
assert.match(profileScreen, /<ProfileSkeleton/);
assert.match(postDetail, /rounded-\[28px\]/);
assert.match(postDetail, /<PostCardSkeleton/);
assert.match(pointDetail, /rounded-\[28px\]/);
assert.match(pointDetail, /Iniciar ruta/);
assert.doesNotMatch(app, /SystemNavigationBackdrop/);
assert.match(app, /SystemNavigationSurface/);
assert.match(app, /height: insets\.bottom/);
assert.match(app, /bg-white/);
assert.equal(appConfig.expo.name, 'ZeroWaste');
assert.equal(appConfig.expo.icon, './assets/branding/zerowaste-icon.png');
assert.equal(appConfig.expo.android.package, 'com.vic45.mobile_app');
assert.equal(appConfig.expo.android.adaptiveIcon.foregroundImage, './assets/branding/zerowaste-adaptive-icon.png');
assert.equal(appConfig.expo.android.softwareKeyboardLayoutMode, 'resize');
assert.deepEqual(appConfig.expo.plugins.find((entry) => Array.isArray(entry) && entry[0] === 'expo-navigation-bar')?.[1], { style: 'dark', enforceContrast: false });
assert.equal(imageUpload.MAX_PROFILE_IMAGE_BYTES, 5 * 1024 * 1024);

console.log('mobile-contracts.test.cjs: mapa, contenido, enlaces, comentarios y push correctos');
