@extends('layouts.admin')
@section('title','Tienda de recompensas') @section('page_title','Tienda de recompensas')
@section('content')
<div class="space-y-6">
    <div class="page-header"><div><p class="text-sm text-slate-500">Catálogo, disponibilidad y stock</p></div><button class="btn-primary" type="button" onclick="rewardCreate.showModal()"><span class="material-symbols-outlined">add</span> Nueva recompensa</button></div>
    @if(session('success'))<div role="status" class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 font-bold text-emerald-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div role="alert" class="rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-800">No fue posible completar la operación. Revisa los campos e inténtalo nuevamente.<ul class="mt-2 list-disc pl-5 font-normal">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form class="glass-card grid gap-3 p-4 md:grid-cols-[1fr_180px_180px_180px_auto]" method="GET"><input class="input-premium" name="q" value="{{ request('q') }}" placeholder="Buscar recompensa…"><select class="input-premium" name="estado"><option value="">Todos los estados</option><option value="activa" @selected(request('estado')==='activa')>Activas</option><option value="inactiva" @selected(request('estado')==='inactiva')>Inactivas</option></select><select class="input-premium" name="stock"><option value="">Cualquier stock</option><option value="con" @selected(request('stock')==='con')>Con stock</option><option value="sin" @selected(request('stock')==='sin')>Sin stock</option></select><select class="input-premium" name="sort"><option value="orden">Orden</option><option value="nombre">Nombre</option><option value="costo_puntos">Costo</option><option value="stock">Stock</option></select><button class="btn-secondary">Filtrar</button></form>
    <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
    @forelse($rows as $row)
        <article class="glass-card overflow-hidden"><div class="aspect-[16/9] bg-white p-5"><img src="{{ \App\Support\Media::url($row->imagen, 'recompensas') }}" alt="{{ $row->nombre }}" loading="lazy" class="h-full w-full rounded-2xl object-contain" onerror="this.closest('div').innerHTML='<div class=&quot;flex h-full items-center justify-center rounded-2xl bg-slate-50 text-slate-400&quot;>Imagen no disponible</div>'"></div><div class="p-5"><div class="flex items-start justify-between gap-3"><h3 class="text-lg font-black dark:text-white">{{ $row->nombre }}</h3><span class="badge-sm {{ $row->activa ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-600' }}">{{ $row->activa ? 'Activa' : 'Inactiva' }}</span></div><p class="mt-2 line-clamp-3 text-sm leading-6 text-slate-500">{{ $row->descripcion }}</p><div class="mt-5 grid grid-cols-4 gap-2 text-center"><div class="rounded-xl bg-slate-50 p-2"><b class="block text-emerald-700">{{ $row->costo_puntos }}</b><small>Puntos</small></div><div class="rounded-xl bg-slate-50 p-2"><b class="block {{ $row->stock === 0 ? 'text-red-600':'text-slate-800' }}">{{ $row->stock }}</b><small>{{ $row->stock === 0 ? 'Agotado':'Stock' }}</small></div><div class="rounded-xl bg-slate-50 p-2"><b class="block">{{ $row->orden }}</b><small>Orden</small></div><div class="rounded-xl bg-slate-50 p-2"><b class="flex min-h-6 items-center justify-center">@if($row->limite_por_usuario){{ $row->limite_por_usuario }}@else<span class="material-symbols-outlined text-xl text-emerald-700" title="Sin límite">all_inclusive</span>@endif</b><small>Límite</small></div></div><div class="mt-5 flex gap-2"><a class="btn-primary flex-1 justify-center" href="{{ route('impacto.recompensas.edit',$row->id) }}"><span class="material-symbols-outlined text-lg">edit</span> Editar</a><button class="btn-secondary" type="button" onclick="retireReward({{ $row->id }})">Retirar</button></div></div></article>
        <form id="retire-{{ $row->id }}" method="POST" action="{{ route('impacto.recompensas.destroy',$row->id) }}" class="hidden">@csrf @method('DELETE')</form>
    @empty<div class="glass-card col-span-full py-16 text-center"><span class="material-symbols-outlined text-5xl text-slate-300">redeem</span><h3 class="mt-3 font-black dark:text-white">No hay recompensas con estos filtros</h3><p class="mt-1 text-sm text-slate-500">Crea una nueva o ajusta la búsqueda.</p></div>@endforelse
    </div>{{ $rows->links() }}
</div>
<dialog id="rewardCreate" class="w-[min(94vw,760px)] max-h-[92vh] overflow-y-auto rounded-[2rem] bg-white p-0 backdrop:bg-slate-950/60 dark:bg-[#0F2A20]"><form method="POST" action="{{ route('impacto.recompensas.store') }}" enctype="multipart/form-data" data-loading-form>@csrf<div class="sticky top-0 z-10 flex items-center justify-between border-b border-emerald-100 bg-gradient-to-r from-emerald-950 to-emerald-800 px-6 py-5 text-white"><div><p class="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Catálogo ZeroWaste</p><h3 class="mt-1 text-2xl font-black">Nueva recompensa</h3><p class="mt-1 text-sm text-emerald-100">Crea una experiencia de canje clara y profesional.</p></div><button type="button" onclick="rewardCreate.close()" class="flex h-11 w-11 items-center justify-center rounded-full bg-white/10 transition hover:bg-white/20" aria-label="Cerrar"><span class="material-symbols-outlined">close</span></button></div><div class="p-6">@include('admin.impacto.partials.reward-fields',['reward'=>null])<div class="mt-6 flex flex-wrap justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" class="btn-secondary" onclick="rewardCreate.close()">Cancelar</button><button class="btn-primary"><span class="material-symbols-outlined text-lg">redeem</span> Crear recompensa</button></div></div></form></dialog>
@endsection
@push('scripts')<script>
async function retireReward(id){const result=await Swal.fire({title:'¿Retirar esta recompensa?',text:'La recompensa dejará de mostrarse en la tienda, pero sus canjes históricos se conservarán.',icon:'warning',showCancelButton:true,confirmButtonText:'Retirar recompensa',cancelButtonText:'Cancelar',confirmButtonColor:'#dc2626'});if(result.isConfirmed)document.getElementById('retire-'+id).requestSubmit();}
document.querySelectorAll('[data-loading-form]').forEach(form=>form.addEventListener('submit',()=>{const button=form.querySelector('button[type=submit],button:not([type])');if(button){button.disabled=true;button.innerHTML='<span class="animate-spin">◌</span> Guardando…';}}));
</script>@endpush
