@extends('layouts.admin')
@section('title','Reglas de puntos') @section('page_title','Reglas de puntos')
@section('content')
<div class="space-y-6">
    <section class="overflow-hidden rounded-[2rem] bg-gradient-to-br from-emerald-950 via-emerald-900 to-emerald-700 p-7 text-white shadow-xl shadow-emerald-950/10">
        <div class="flex flex-wrap items-end justify-between gap-5"><div class="max-w-2xl"><p class="text-xs font-black uppercase tracking-[.22em] text-emerald-300">Motor de impacto</p><h2 class="mt-2 text-3xl font-black">Puntos transparentes y auditables</h2><p class="mt-3 leading-6 text-emerald-100">FastAPI toma el monto de la regla activa. Cada modificación conserva su historial y nunca cambia movimientos anteriores.</p></div><button class="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-white px-5 font-black text-emerald-900 shadow-lg transition hover:-translate-y-0.5" type="button" onclick="newRule.showModal()"><span class="material-symbols-outlined">add_circle</span>Nueva regla</button></div>
    </section>

    @if(session('success'))<div role="status" class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 font-bold text-emerald-800"><span class="material-symbols-outlined mr-2 align-middle text-emerald-600">check_circle</span>{{ session('success') }}</div>@endif
    @if(session('error'))<div role="alert" class="rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-red-800">{{ session('error') }}</div>@endif
    @if($errors->any())<div role="alert" class="rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-red-800">No fue posible crear la regla.<ul class="mt-2 list-disc pl-5 font-normal">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="GET" class="glass-card grid gap-3 p-4 md:grid-cols-[1fr_190px_auto]"><label class="relative"><span class="material-symbols-outlined absolute left-4 top-3.5 text-slate-400">search</span><input class="input-premium pl-12" name="q" value="{{ request('q') }}" placeholder="Buscar código o descripción"></label><select class="input-premium" name="estado"><option value="">Todos los estados</option><option value="activa" @selected(request('estado')==='activa')>Activas</option><option value="inactiva" @selected(request('estado')==='inactiva')>Inactivas</option></select><button class="btn-secondary justify-center"><span class="material-symbols-outlined text-lg">filter_alt</span>Filtrar</button></form>

    <div class="grid gap-5 lg:grid-cols-2">
        @forelse($rows as $row)
        <article class="glass-card group overflow-hidden border border-slate-100 p-0 transition hover:-translate-y-0.5 hover:shadow-xl dark:border-emerald-900">
            <div class="h-1.5 {{ $row->activa ? 'bg-emerald-500' : 'bg-slate-300' }}"></div>
            <div class="p-6"><div class="flex items-start justify-between gap-4"><div class="min-w-0"><div class="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700 dark:bg-emerald-900/40"><span class="material-symbols-outlined">toll</span></div><code class="mt-4 block break-all text-sm font-black tracking-wide text-emerald-700">{{ $row->codigo }}</code><p class="mt-2 text-sm leading-6 text-slate-500">{{ $row->descripcion }}</p></div><span class="inline-flex shrink-0 items-center gap-1 rounded-full px-3 py-1.5 text-xs font-black {{ $row->activa?'bg-emerald-100 text-emerald-800':'bg-slate-100 text-slate-600' }}"><span class="material-symbols-outlined text-base">{{ $row->activa ? 'check_circle' : 'pause_circle' }}</span>{{ $row->activa?'Activa':'Inactiva' }}</span></div>
                <div class="mt-5 grid grid-cols-2 gap-3 border-t border-slate-100 pt-5 dark:border-emerald-900"><div class="rounded-2xl bg-emerald-50 p-4 dark:bg-emerald-950/30"><span class="text-xs font-black uppercase tracking-wider text-emerald-700">Premio</span><b class="mt-1 block text-2xl text-emerald-800 dark:text-emerald-300">{{ number_format($row->puntos) }} pts</b></div><div class="rounded-2xl bg-slate-50 p-4 dark:bg-white/5"><span class="text-xs font-black uppercase tracking-wider text-slate-500">Frecuencia</span><b class="mt-1 block text-sm text-slate-800 dark:text-white">{{ $row->limite_diario ? $row->limite_diario.' al día' : 'Sin límite diario' }}</b></div></div>
                <div class="mt-5 flex justify-end"><a class="btn-primary" href="{{ route('impacto.reglas.edit',$row->id) }}"><span class="material-symbols-outlined text-lg">edit</span>Editar regla</a></div>
            </div>
        </article>
        @empty<div class="glass-card py-16 text-center lg:col-span-2"><span class="material-symbols-outlined text-5xl text-slate-300">rule</span><h3 class="mt-3 font-black text-slate-800 dark:text-white">No hay reglas con estos filtros</h3><p class="mt-1 text-sm text-slate-500">Ajusta la búsqueda o crea una regla nueva.</p></div>@endforelse
    </div>
    {{ $rows->links() }}

    <section class="glass-card overflow-hidden"><div class="border-b border-slate-100 p-5 dark:border-emerald-900"><h3 class="flex items-center gap-2 font-black dark:text-white"><span class="material-symbols-outlined text-emerald-600">history</span>Historial de cambios</h3><p class="mt-1 text-sm text-slate-500">Trazabilidad administrativa en horario de Querétaro.</p></div><div class="overflow-x-auto"><table class="premium-table"><thead><tr><th>Regla</th><th>Administrador</th><th>Fecha</th></tr></thead><tbody>@forelse($history as $item)<tr><td><span class="rounded-lg bg-emerald-50 px-2 py-1 font-black text-emerald-700">#{{ $item->rule_id }}</span></td><td>{{ $item->administrator ?? 'Sistema' }}</td><td>{{ \Illuminate\Support\Carbon::parse($item->created_at)->timezone('America/Mexico_City')->translatedFormat('j M Y, g:i a') }}</td></tr>@empty<tr><td colspan="3" class="py-10 text-center text-slate-500">Sin cambios registrados.</td></tr>@endforelse</tbody></table></div></section>
</div>

<dialog id="newRule" class="w-[min(94vw,620px)] rounded-[2rem] bg-white p-0 backdrop:bg-slate-950/60 dark:bg-[#0F2A20]"><form method="POST" action="{{ route('impacto.reglas.store') }}">@csrf<div class="flex items-center justify-between rounded-t-[2rem] bg-emerald-950 px-6 py-5 text-white"><div><p class="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Motor de impacto</p><h3 class="mt-1 text-2xl font-black">Nueva regla de puntos</h3></div><button type="button" onclick="newRule.close()" class="flex h-10 w-10 items-center justify-center rounded-full bg-white/10" aria-label="Cerrar"><span class="material-symbols-outlined">close</span></button></div><div class="space-y-5 p-6"><label class="block text-sm font-bold">Código interno<input class="input-premium mt-1 uppercase" name="codigo" maxlength="60" pattern="[A-Z0-9_]+" value="{{ old('codigo') }}" placeholder="EJ. RECOLECCION_QR" required><span class="mt-1 block text-xs font-medium text-slate-400">Sólo mayúsculas, números y guion bajo.</span></label><label class="block text-sm font-bold">Descripción<textarea class="input-premium mt-1" name="descripcion" rows="3" maxlength="255" data-rule-word-limit="35" placeholder="Explica cuándo se otorgan los puntos" required>{{ old('descripcion') }}</textarea><span class="mt-1 flex justify-between text-xs font-medium text-slate-400"><span>Describe una sola condición verificable.</span><span data-rule-word-counter>0 / 35 palabras</span></span></label><div class="grid grid-cols-2 gap-3"><label class="text-sm font-bold">Puntos<input class="input-premium mt-1" type="number" min="0" max="100000" name="puntos" value="{{ old('puntos') }}" required></label><label class="text-sm font-bold">Límite diario<input class="input-premium mt-1" type="number" min="1" max="1000" name="limite_diario" value="{{ old('limite_diario') }}" placeholder="Sin límite"></label></div><label class="flex min-h-14 items-center gap-3 rounded-2xl border border-emerald-100 bg-emerald-50 px-4 font-bold"><input type="hidden" name="activa" value="0"><input class="h-5 w-5 accent-emerald-600" type="checkbox" name="activa" value="1" @checked((bool) old('activa', true))><span><span class="block">Activar al crear</span><small class="font-medium text-slate-500">El backend podrá usarla inmediatamente.</small></span></label><div class="flex justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" class="btn-secondary" onclick="newRule.close()">Cancelar</button><button class="btn-primary"><span class="material-symbols-outlined text-lg">add_circle</span>Crear regla</button></div></div></form></dialog>
@endsection
@push('scripts')<script>
document.querySelectorAll('[data-rule-word-limit]').forEach(field=>{const counter=field.parentElement.querySelector('[data-rule-word-counter]');const update=()=>{const maximum=Number(field.dataset.ruleWordLimit);const count=(field.value.trim().match(/[\p{L}\p{N}]+(?:[’'-][\p{L}\p{N}]+)*/gu)||[]).length;counter.textContent=`${count} / ${maximum} palabras`;counter.classList.toggle('text-red-600',count>maximum);field.setCustomValidity(count>maximum?`Usa un máximo de ${maximum} palabras.`:'');};field.addEventListener('input',update);update();});
@if($errors->any()) document.getElementById('newRule')?.showModal(); @endif
</script>@endpush
