@extends('layouts.admin')
@section('title','Reglas de puntos') @section('page_title','Reglas de puntos')
@section('content')
<div class="space-y-6"><div class="page-header"><p class="max-w-2xl text-sm text-slate-500">El backend calcula cada premio a partir de estas reglas. Los códigos con movimientos conservan su identidad.</p><button class="btn-primary" onclick="newRule.showModal()"><span class="material-symbols-outlined">add</span> Nueva regla</button></div>
@if(session('success'))<div role="status" class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 font-bold text-emerald-800">{{ session('success') }}</div>@endif
<form method="GET" class="glass-card grid gap-3 p-4 md:grid-cols-[1fr_180px_auto]"><input class="input-premium" name="q" value="{{ request('q') }}" placeholder="Buscar código o descripción"><select class="input-premium" name="estado"><option value="">Todas</option><option value="activa">Activas</option><option value="inactiva">Inactivas</option></select><button class="btn-secondary">Filtrar</button></form>
    <div class="grid gap-4 lg:grid-cols-2">@forelse($rows as $row)<article class="glass-card p-5"><div class="flex items-start justify-between gap-4"><div class="min-w-0"><code class="font-black text-emerald-700">{{ $row->codigo }}</code><p class="mt-2 text-sm leading-6 text-slate-500">{{ $row->descripcion }}</p></div><span class="badge-sm shrink-0 {{ $row->activa?'bg-emerald-100 text-emerald-800':'bg-slate-100 text-slate-600' }}">{{ $row->activa?'Activa':'Inactiva' }}</span></div><div class="mt-5 flex items-end justify-between border-t border-slate-100 pt-4 dark:border-emerald-900"><div><b class="block text-2xl text-emerald-700">{{ $row->puntos }} puntos</b><span class="text-xs font-semibold text-slate-500">{{ $row->limite_diario ? 'Límite de '.$row->limite_diario.' al día' : 'Sin límite diario' }}</span></div><a class="btn-primary" href="{{ route('impacto.reglas.edit',$row->id) }}"><span class="material-symbols-outlined text-lg">edit</span> Editar</a></div></article>@empty<div class="glass-card py-12 text-center lg:col-span-2">No hay reglas con estos filtros.</div>@endforelse</div>{{ $rows->links() }}
<section class="glass-card p-5"><h3 class="font-black dark:text-white">Historial de cambios</h3><div class="mt-4 overflow-x-auto"><table class="premium-table"><thead><tr><th>Regla</th><th>Administrador</th><th>Fecha</th></tr></thead><tbody>@forelse($history as $item)<tr><td>#{{ $item->rule_id }}</td><td>{{ $item->administrator ?? 'Sistema' }}</td><td>{{ \Illuminate\Support\Carbon::parse($item->created_at)->timezone('America/Mexico_City')->translatedFormat('j M Y, g:i a') }}</td></tr>@empty<tr><td colspan="3" class="py-8 text-center">Sin cambios registrados.</td></tr>@endforelse</tbody></table></div></section></div>
<dialog id="newRule" class="w-[min(92vw,520px)] rounded-3xl p-0 backdrop:bg-black/50"><form method="POST" action="{{ route('impacto.reglas.store') }}" class="space-y-4 p-6">@csrf<h3 class="text-xl font-black">Nueva regla</h3><label class="text-sm font-bold">Código interno<input class="input-premium mt-1 uppercase" name="codigo" pattern="[A-Z0-9_]+" required></label><label class="text-sm font-bold">Descripción<input class="input-premium mt-1" name="descripcion" required></label><div class="grid grid-cols-2 gap-3"><label class="text-sm font-bold">Puntos<input class="input-premium mt-1" type="number" min="0" name="puntos" required></label><label class="text-sm font-bold">Límite diario<input class="input-premium mt-1" type="number" min="1" name="limite_diario"></label></div><label class="font-bold"><input type="checkbox" name="activa" value="1"> Activa</label><div class="flex justify-end gap-3"><button type="button" class="btn-secondary" onclick="newRule.close()">Cancelar</button><button class="btn-primary">Crear regla</button></div></form></dialog>
@endsection
